import React from 'react';
import {
  UtensilsCrossed,
  ShoppingCart,
  Zap,
  Sparkles,
  Home,
  HeartPulse,
  Car,
  Shirt,
  GraduationCap,
  ShoppingBag,
  BadgeDollarSign,
  Coins,
  Gift,
  ArrowRightLeft,
  Tag,
  CreditCard,
  Wallet,
  Coffee,
  Plane,
  Briefcase,
  Smartphone,
  BookOpen,
  Music,
  Shield,
  ShieldCheck,
  HelpCircle,
  Dumbbell,
  Fuel,
  Bus,
  Train,
  Film,
  Gamepad2,
  Tv,
  Baby,
  Dog,
  Cat,
  Scissors,
  Wrench,
  Book,
  FileText,
  Camera,
  Laptop,
  PiggyBank,
  TrendingUp,
  Percent,
  Heart,
  Smile,
  Star,
  Wifi,
  Flame,
  LucideProps,
} from 'lucide-react';

interface CategoryIconProps extends LucideProps {
  name: string;
}

const ICON_MAP: Record<string, React.FC<LucideProps>> = {
  UtensilsCrossed,
  ShoppingCart,
  Zap,
  Sparkles,
  Home,
  HeartPulse,
  Car,
  Shirt,
  GraduationCap,
  ShoppingBag,
  BadgeDollarSign,
  Coins,
  Gift,
  ArrowRightLeft,
  Tag,
  CreditCard,
  Wallet,
  Coffee,
  Plane,
  Briefcase,
  Smartphone,
  BookOpen,
  Music,
  Shield,
  ShieldCheck,
  HelpCircle,
  Dumbbell,
  Fuel,
  Bus,
  Train,
  Film,
  Gamepad2,
  Tv,
  Baby,
  Dog,
  Cat,
  Scissors,
  Wrench,
  Book,
  FileText,
  Camera,
  Laptop,
  PiggyBank,
  TrendingUp,
  Percent,
  Heart,
  Smile,
  Star,
  Wifi,
  Flame,
};

export const AVAILABLE_CATEGORY_ICONS = [
  { name: 'UtensilsCrossed', label: 'Dining' },
  { name: 'Coffee', label: 'Coffee / Drinks' },
  { name: 'ShoppingCart', label: 'Groceries' },
  { name: 'ShoppingBag', label: 'Shopping' },
  { name: 'Car', label: 'Transport' },
  { name: 'Fuel', label: 'Fuel / Gas' },
  { name: 'Bus', label: 'Bus' },
  { name: 'Train', label: 'Train / MRT' },
  { name: 'Plane', label: 'Travel / Flights' },
  { name: 'Home', label: 'Housing' },
  { name: 'Zap', label: 'Utilities / Power' },
  { name: 'Wifi', label: 'Internet' },
  { name: 'Sparkles', label: 'Entertainment' },
  { name: 'Film', label: 'Movies / Streaming' },
  { name: 'Tv', label: 'TV' },
  { name: 'Gamepad2', label: 'Gaming' },
  { name: 'Music', label: 'Music' },
  { name: 'HeartPulse', label: 'Health / Medical' },
  { name: 'Dumbbell', label: 'Fitness / Gym' },
  { name: 'ShieldCheck', label: 'Insurance' },
  { name: 'Shield', label: 'Security' },
  { name: 'Shirt', label: 'Clothing' },
  { name: 'GraduationCap', label: 'Education' },
  { name: 'BookOpen', label: 'Books' },
  { name: 'BadgeDollarSign', label: 'Salary' },
  { name: 'Coins', label: 'Side Income' },
  { name: 'PiggyBank', label: 'Savings' },
  { name: 'TrendingUp', label: 'Investments' },
  { name: 'Gift', label: 'Gifts' },
  { name: 'Baby', label: 'Kids / Baby' },
  { name: 'Dog', label: 'Pets' },
  { name: 'Cat', label: 'Cat' },
  { name: 'Scissors', label: 'Personal Care' },
  { name: 'Wrench', label: 'Maintenance' },
  { name: 'Smartphone', label: 'Mobile / Phone' },
  { name: 'Laptop', label: 'Electronics' },
  { name: 'CreditCard', label: 'Credit Card' },
  { name: 'Wallet', label: 'Wallet / Cash' },
  { name: 'ArrowRightLeft', label: 'Transfer' },
  { name: 'Tag', label: 'General / Tag' },
  { name: 'Star', label: 'Special' },
  { name: 'Heart', label: 'Love' },
];

export function CategoryIcon({ name, ...props }: CategoryIconProps) {
  const IconComponent = ICON_MAP[name] || Tag;
  return <IconComponent {...props} />;
}
